version: '3'
services:
  app:
    build: .
    ports:
    - "$APP_HTTP_HOST_PORT:8080"
    - "$APP_DEBUG_HOST_PORT:8000"
    environment:
    - "JAVA_OPTS=\"-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n\""
    - "DATABASE_HOST_NAME=$DATABASE_HOST_NAME"
    - "DATABASE_PORT=5432"
    - "PGUSER=biblivre"
    - "PGPASSWORD=$POSTGRES_PASSWORD"
    - "PGDATABASE=$POSTGRES_DB"
    - "DIGITAL_MEDIA_DAO_IMPL=$DIGITAL_MEDIA_DAO_IMPL"
    depends_on:
    - database
    command: sh -c 'wait-for.sh -t 30 database:5432 -- /usr/local/tomcat/bin/catalina.sh run'
  database:
    image: postgres:11
    ports:
    - "$DATABASE_HOST_PORT:5432"
    volumes:
    - "./sql/biblivre4.sql:/docker-entrypoint-initdb.d/populate-initial-data.sql"
    environment:
    - "POSTGRES_USER=biblivre"
    - "POSTGRES_PASSWORD=$POSTGRES_PASSWORD"
    - "POSTGRES_DB=$POSTGRES_DB"

  web:
    image: nginx
    ports:
    - "$WEB_HTTP_HOST_PORT:80"
    volumes:
    - "./nginx/conf.d/:/etc/nginx/conf.d/"
    depends_on:
    - app
